language: cpp
compiler:
  - gcc
  - clang
branches:
  only:
    - master
before_install:
  - yes | sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-proper
  - sudo apt-get update
  - sudo apt-get install libraw-dev imagemagick libmagick++-dev qtbase5-dev qtchooser

script: qtchooser -run-tool=qmake -qt=qt5 && make && cd ./tests/build/debug/ && ./tst_imagetest
