language: cpp
compiler:
  - gcc-4.8
  - clang
branches:
  only:
    - master
before_install:
  - yes | sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-proper
  - sudo apt-get update
  - sudo apt-get install libraw-dev imagemagick libmagick++-dev qtbase5-dev qtchooser
  - sudo pip install cpp-coveralls --use-mirrors

script: 
  - qtchooser -run-tool=qmake -qt=qt5
  - make
  - make check

after_success:
  - coveralls --exclude tests --exclude-pattern '.*\.moc'
